name: ProDreamAPP
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icon/iconearenaofvalor.png
    - assets/icon/iconeclashroyale.png
    - assets/icon/iconecsgo.png
    - assets/icon/iconedota.png
    - assets/icon/iconefortnite.png
    - assets/icon/iconefreefire.png
    - assets/icon/iconelol.png
    - assets/icon/iconepubg.png
    - assets/icon/iconetft.png
    - assets/icon/iconevainglory.png
    - assets/icon/iconevalorant.png
    - assets/icon/iconebrawlstars.png
    - assets/icon/iconelogo.png
    - assets/icon/iconelogotransparente.png
    - assets/icon/iconecallofdutymobile.png
    - assets/icon/iconecallofdutywarzone.png
    - assets/icon/iconehearthstone.png
    - assets/icon/iconelegendsofruneterra.png
    - assets/icon/iconemobilelegends.png
    - assets/icon/iconeoverwatch.png
    - assets/icon/iconetaca.png
    - assets/icon/iconetacatransparente.png
    - assets/flags/afghanistan-flag-icon-32.png
    - assets/flags/albania-flag-icon-32.png
    - assets/flags/algeria-flag-icon-32.png
    - assets/flags/andorra-flag-icon-32.png
    - assets/flags/angola-flag-icon-32.png
    - assets/flags/antigua-and-barbuda-flag-icon-32.png
    - assets/flags/argentina-flag-icon-32.png
    - assets/flags/armenia-flag-icon-32.png
    - assets/flags/australia-flag-icon-32.png
    - assets/flags/austria-flag-icon-32.png
    - assets/flags/azerbaijan-flag-icon-32.png
    - assets/flags/bahamas-flag-icon-32.png
    - assets/flags/bahrain-flag-icon-32.png
    - assets/flags/bangladesh-flag-icon-32.png
    - assets/flags/barbados-flag-icon-32.png
    - assets/flags/belarus-flag-icon-32.png
    - assets/flags/belgium-flag-icon-32.png
    - assets/flags/belize-flag-icon-32.png
    - assets/flags/benin-flag-icon-32.png
    - assets/flags/bhutan-flag-icon-32.png
    - assets/flags/bolivia-flag-icon-32.png
    - assets/flags/bosnia-and-herzegovina-flag-icon-32.png
    - assets/flags/botswana-flag-icon-32.png
    - assets/flags/brazil-flag-icon-32.png
    - assets/flags/brunei-flag-icon-32.png
    - assets/flags/bulgaria-flag-icon-32.png
    - assets/flags/burkina-faso-flag-icon-32.png
    - assets/flags/burundi-flag-icon-32.png
    - assets/flags/cambodia-flag-icon-32.png
    - assets/flags/cameroon-flag-icon-32.png
    - assets/flags/canada-flag-icon-32.png
    - assets/flags/cape-verde-flag-icon-32.png
    - assets/flags/central-african-republic-flag-icon-32.png
    - assets/flags/chad-flag-icon-32.png
    - assets/flags/chile-flag-icon-32.png
    - assets/flags/china-flag-icon-32.png
    - assets/flags/colombia-flag-icon-32.png
    - assets/flags/comoros-flag-icon-32.png
    - assets/flags/congo-democratic-republic-of-the-flag-icon-32.png
    - assets/flags/congo-republic-of-the-flag-icon-32.png
    - assets/flags/costa-rica-flag-icon-32.png
    - assets/flags/cote-d-ivoire-flag-icon-32.png
    - assets/flags/croatia-flag-icon-32.png
    - assets/flags/cuba-flag-icon-32.png
    - assets/flags/cyprus-flag-icon-32.png
    - assets/flags/czech-republic-flag-icon-32.png
    - assets/flags/denmark-flag-icon-32.png
    - assets/flags/djibouti-flag-icon-32.png
    - assets/flags/dominica-flag-icon-32.png
    - assets/flags/dominican-republic-flag-icon-32.png
    - assets/flags/east-timor-flag-icon-32.png
    - assets/flags/ecuador-flag-icon-32.png
    - assets/flags/egypt-flag-icon-32.png
    - assets/flags/el-salvador-flag-icon-32.png
    - assets/flags/equatorial-guinea-flag-icon-32.png
    - assets/flags/eritrea-flag-icon-32.png
    - assets/flags/estonia-flag-icon-32.png
    - assets/flags/ethiopia-flag-icon-32.png
    - assets/flags/fiji-flag-icon-32.png
    - assets/flags/finland-flag-icon-32.png
    - assets/flags/france-flag-icon-32.png
    - assets/flags/gabon-flag-icon-32.png
    - assets/flags/gambia-flag-icon-32.png
    - assets/flags/georgia-flag-icon-32.png
    - assets/flags/germany-flag-icon-32.png
    - assets/flags/ghana-flag-icon-32.png
    - assets/flags/greece-flag-icon-32.png
    - assets/flags/grenada-flag-icon-32.png
    - assets/flags/guatemala-flag-icon-32.png
    - assets/flags/guinea-bissau-flag-icon-32.png
    - assets/flags/guinea-flag-icon-32.png
    - assets/flags/guyana-flag-icon-32.png
    - assets/flags/haiti-flag-icon-32.png
    - assets/flags/honduras-flag-icon-32.png
    - assets/flags/hungary-flag-icon-32.png
    - assets/flags/iceland-flag-icon-32.png
    - assets/flags/india-flag-icon-32.png
    - assets/flags/indonesia-flag-icon-32.png
    - assets/flags/iran-flag-icon-32.png
    - assets/flags/iraq-flag-icon-32.png
    - assets/flags/ireland-flag-icon-32.png
    - assets/flags/israel-flag-icon-32.png
    - assets/flags/italy-flag-icon-32.png
    - assets/flags/jamaica-flag-icon-32.png
    - assets/flags/japan-flag-icon-32.png
    - assets/flags/jordan-flag-icon-32.png
    - assets/flags/kazakhstan-flag-icon-32.png
    - assets/flags/kenya-flag-icon-32.png
    - assets/flags/kiribati-flag-icon-32.png
    - assets/flags/kuwait-flag-icon-32.png
    - assets/flags/kyrgyzstan-flag-icon-32.png
    - assets/flags/laos-flag-icon-32.png
    - assets/flags/latvia-flag-icon-32.png
    - assets/flags/lebanon-flag-icon-32.png
    - assets/flags/lesotho-flag-icon-32.png
    - assets/flags/liberia-flag-icon-32.png
    - assets/flags/libya-flag-icon-32.png
    - assets/flags/liechtenstein-flag-icon-32.png
    - assets/flags/lithuania-flag-icon-32.png
    - assets/flags/luxembourg-flag-icon-32.png
    - assets/flags/macedonia-flag-icon-32.png
    - assets/flags/madagascar-flag-icon-32.png
    - assets/flags/malawi-flag-icon-32.png
    - assets/flags/malaysia-flag-icon-32.png
    - assets/flags/maldives-flag-icon-32.png
    - assets/flags/mali-flag-icon-32.png
    - assets/flags/malta-flag-icon-32.png
    - assets/flags/marshall-islands-flag-icon-32.png
    - assets/flags/mauritania-flag-icon-32.png
    - assets/flags/mauritius-flag-icon-32.png
    - assets/flags/mexico-flag-icon-32.png
    - assets/flags/micronesia-flag-icon-32.png
    - assets/flags/moldova-flag-icon-32.png
    - assets/flags/monaco-flag-icon-32.png
    - assets/flags/mongolia-flag-icon-32.png
    - assets/flags/montenegro-flag-icon-32.png
    - assets/flags/morocco-flag-icon-32.png
    - assets/flags/mozambique-flag-icon-32.png
    - assets/flags/myanmar-flag-icon-32.png
    - assets/flags/namibia-flag-icon-32.png
    - assets/flags/nauru-flag-icon-32.png
    - assets/flags/nepal-flag-icon-32.png
    - assets/flags/netherlands-flag-icon-32.png
    - assets/flags/new-zealand-flag-icon-32.png
    - assets/flags/nicaragua-flag-icon-32.png
    - assets/flags/niger-flag-icon-32.png
    - assets/flags/nigeria-flag-icon-32.png
    - assets/flags/niue-flag-icon-32.png
    - assets/flags/north-korea-flag-icon-32.png
    - assets/flags/norway-flag-icon-32.png
    - assets/flags/oman-flag-icon-32.png
    - assets/flags/pakistan-flag-icon-32.png
    - assets/flags/palau-flag-icon-32.png
    - assets/flags/panama-flag-icon-32.png
    - assets/flags/papua-new-guinea-flag-icon-32.png
    - assets/flags/paraguay-flag-icon-32.png
    - assets/flags/peru-flag-icon-32.png
    - assets/flags/philippines-flag-icon-32.png
    - assets/flags/poland-flag-icon-32.png
    - assets/flags/portugal-flag-icon-32.png
    - assets/flags/qatar-flag-icon-32.png
    - assets/flags/romania-flag-icon-32.png
    - assets/flags/russia-flag-icon-32.png
    - assets/flags/rwanda-flag-icon-32.png
    - assets/flags/saint-kitts-and-nevis-flag-icon-32.png
    - assets/flags/saint-lucia-flag-icon-32.png
    - assets/flags/saint-vincent-and-the-grenadines-flag-icon-32.png
    - assets/flags/samoa-flag-icon-32.png
    - assets/flags/san-marino-flag-icon-32.png
    - assets/flags/sao-tome-and-principe-flag-icon-32.png
    - assets/flags/saudi-arabia-flag-icon-32.png
    - assets/flags/senegal-flag-icon-32.png
    - assets/flags/serbia-flag-icon-32.png
    - assets/flags/seychelles-flag-icon-32.png
    - assets/flags/sierra-leone-flag-icon-32.png
    - assets/flags/singapore-flag-icon-32.png
    - assets/flags/slovakia-flag-icon-32.png
    - assets/flags/slovenia-flag-icon-32.png
    - assets/flags/solomon-islands-flag-icon-32.png
    - assets/flags/somalia-flag-icon-32.png
    - assets/flags/south-africa-flag-icon-32.png
    - assets/flags/south-korea-flag-icon-32.png
    - assets/flags/south-sudan-flag-icon-32.png
    - assets/flags/spain-flag-icon-32.png
    - assets/flags/sri-lanka-flag-icon-32.png
    - assets/flags/sudan-flag-icon-32.png
    - assets/flags/suriname-flag-icon-32.png
    - assets/flags/swaziland-flag-icon-32.png
    - assets/flags/sweden-flag-icon-32.png
    - assets/flags/switzerland-flag-icon-32.png
    - assets/flags/syria-flag-icon-32.png
    - assets/flags/taiwan-flag-icon-32.png
    - assets/flags/tajikistan-flag-icon-32.png
    - assets/flags/tanzania-flag-icon-32.png
    - assets/flags/thailand-flag-icon-32.png
    - assets/flags/togo-flag-icon-32.png
    - assets/flags/tonga-flag-icon-32.png
    - assets/flags/trinidad-and-tobago-flag-icon-32.png
    - assets/flags/tunisia-flag-icon-32.png
    - assets/flags/turkey-flag-icon-32.png
    - assets/flags/turkmenistan-flag-icon-32.png
    - assets/flags/tuvalu-flag-icon-32.png
    - assets/flags/uganda-flag-icon-32.png
    - assets/flags/ukraine-flag-icon-32.png
    - assets/flags/united-arab-emirates-flag-icon-32.png
    - assets/flags/united-kingdom-flag-icon-32.png
    - assets/flags/united-states-of-america-flag-icon-32.png
    - assets/flags/uruguay-flag-icon-32.png
    - assets/flags/uzbekistan-flag-icon-32.png
    - assets/flags/vatican-city-flag-icon-32.png
    - assets/flags/venezuela-flag-icon-32.png
    - assets/flags/vietnam-flag-icon-32.png
    - assets/flags/yemen-flag-icon-32.png
    - assets/flags/zambia-flag-icon-32.png
    - assets/flags/zimbabwe-flag-icon-32.png

    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
        - asset: assets/fonts/OpenSans-Light.ttf
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-SemiBold.ttf
    - family: Merriweather
      fonts:
        - asset: assets/fonts/Merriweather-Black.ttf
        - asset: assets/fonts/Merriweather-Bold.ttf
        - asset: assets/fonts/Merriweather-Regular.ttf
        - asset: assets/fonts/Merriweather-Light.ttf 
    - family: Righteous
      fonts:
        - asset: assets/fonts/Righteous-Regular.ttf
    - family: BreeSerif
      fonts:
        - asset: assets/fonts/BreeSerif-Regular.ttf

  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
