import 'package:flutter/material.dart';

class Country {
  final String name;
  final String flag;

  Country(this.name, this.flag);
}

List<Country> countries = [
Country("Afghanistan", "assets/flags/afghanistan-flag-icon-32.png"),
Country("Albania","assets/flags/albania-flag-icon-32.png" ),
Country("Algeria","assets/flags/algeria-flag-icon-32.png" ),
Country("Andorra","assets/flags/andorra-flag-icon-32.png" ),
Country("Angola","assets/flags/angola-flag-icon-32.png" ),
Country("Argentina","assets/flags/argentina-flag-icon-32.png"),
Country("Armenia","assets/flags/armenia-flag-icon-32.png"),
Country("Australia","assets/flags/australia-flag-icon-32.png"),
Country("Austria","assets/flags/austria-flag-icon-32.png"),
Country("Azerbaijan","assets/flags/azerbaijan-flag-icon-32.png"),
Country("Bahamas","assets/flags/bahamas-flag-icon-32.png"),
Country("Bahrain","assets/flags/bahrain-flag-icon-32.png"),
Country("Bangladesh","assets/flags/bangladesh-flag-icon-32.png"),
Country("Barbados","assets/flags/barbados-flag-icon-32.png"),
Country("Belarus","assets/flags/belarus-flag-icon-32.png"),
Country("Belgium","assets/flags/belgium-flag-icon-32.png"),
Country("Belize","assets/flags/belize-flag-icon-32.png"),
Country("Benin","assets/flags/benin-flag-icon-32.png"),
Country("Bhutan","assets/flags/bhutan-flag-icon-32.png"),
Country("Bolivia","assets/flags/bolivia-flag-icon-32.png"),
Country("Bosnia and Herzegovina","assets/flags/bosnia-and-herzegovina-flag-icon-32.png"),
Country("Botswana","assets/flags/botswana-flag-icon-32.png"),
Country("Brazil","assets/flags/brazil-flag-icon-32.png"),
Country("Brunei","assets/flags/brunei-flag-icon-32.png"),
Country("Bulgaria","assets/flags/bulgaria-flag-icon-32.png"),
Country("Burkina Faso","assets/flags/burkina-faso-flag-icon-32.png"),
Country("Burma","assets/flags/burma-flag-icon-32.png"),
Country("Burundi","assets/flags/burundi-flag-icon-32.png"),
Country("Cambodia","assets/flags/cambodia-flag-icon-32.png"),
Country("Cameroon","assets/flags/cameroon-flag-icon-32.png"),
Country("Canada","assets/flags/canada-flag-icon-32.png"),
Country("Cape Verde","assets/flags/cape-verde-flag-icon-32.png"),
Country("Chad","assets/flags/chad-flag-icon-32.png"),
Country("Chile","assets/flags/chile-flag-icon-32.png"),
Country("China","assets/flags/china-flag-icon-32.png"),
Country("Colombia","assets/flags/colombia-flag-icon-32.png"),
Country("Congo","assets/flags/congo-democratic-republic-of-the-flag-icon-32.png"),
Country("Costa Rica","assets/flags/costa-rica-flag-icon-32.png"),
Country("Croatia","assets/flags/croatia-flag-icon-32.png"),
Country("Cuba","assets/flags/cuba-flag-icon-32.png"),
Country("Cyprus","assets/flags/cyprus-flag-icon-32.png"),
Country("Czech Republic","assets/flags/czech-republic-flag-icon-32.png"),
Country("Denmark","assets/flags/denmark-flag-icon-32.png"),
Country("Djibouti","assets/flags/djibouti-flag-icon-32.png"),
Country("Dominica","assets/flags/dominica-flag-icon-32.png"),
Country("Dominican Republic","assets/flags/dominican-republic-flag-icon-32.png"),
Country("Ecuador","assets/flags/ecuador-flag-icon-32.png"),
Country("Egypt","assets/flags/egypt-flag-icon-32.png"),
Country("El Salvador","assets/flags/el-salvador-flag-icon-32.png"),
Country("England","assets/flags/england-flag-icon-32.png"),
Country("Eritrea","assets/flags/eritrea-flag-icon-32.png"),
Country("Estonia","assets/flags/estonia-flag-icon-32.png"),
Country("Ethiopia","assets/flags/ethiopia-flag-icon-32.png"),
Country("Fiji","assets/flags/fiji-flag-icon-32.png"),
Country("Finland","assets/flags/finland-flag-icon-32.png"),
Country("France","assets/flags/france-flag-icon-32.png"),
Country("Gabon","assets/flags/gabon-flag-icon-32.png"),
Country("Gambia","assets/flags/gambia-flag-icon-32.png"),
Country("Georgia","assets/flags/georgia-flag-icon-32.png"),
Country("Germany","assets/flags/germany-flag-icon-32.png"),
Country("Ghana","assets/flags/ghana-flag-icon-32.png"),
Country("Greece","assets/flags/greece-flag-icon-32.png"),
Country("Grenada","assets/flags/grenada-flag-icon-32.png"),
Country("Guatemala","assets/flags/guatemala-flag-icon-32.png"),
Country("Guinea","assets/flags/guinea-flag-icon-32.png"),
Country("Guyana","assets/flags/guyana-flag-icon-32.png"),
Country("Haiti","assets/flags/haiti-flag-icon-32.png"),
Country("Holland","assets/flags/holland-flag-icon-32.png"),
Country("Honduras","assets/flags/honduras-flag-icon-32.png"),
Country("Hungary","assets/flags/hungary-flag-icon-32.png"),
Country("Iceland","assets/flags/iceland-flag-icon-32.png"),
Country("India","assets/flags/india-flag-icon-32.png"),
Country("Indonesia","assets/flags/indonesia-flag-icon-32.png"),
Country("Iran","assets/flags/iran-flag-icon-32.png"),
Country("Iraq","assets/flags/iraq-flag-icon-32.png"),
Country("Ireland","assets/flags/ireland-flag-icon-32.png"),
Country("Israel","assets/flags/israel-flag-icon-32.png"),
Country("Italy","assets/flags/italy-flag-icon-32.png"),
Country("Japan","assets/flags/japan-flag-icon-32.png"),
Country("Jordan","assets/flags/jordan-flag-icon-32.png"),
Country("Kazakhstan","assets/flags/kazakhstan-flag-icon-32.png"),
Country("Kenya","assets/flags/kenya-flag-icon-32.png"),
Country("Kuwait","assets/flags/kuwait-flag-icon-32.png"),
Country("Laos","assets/flags/laos-flag-icon-32.png"),
Country("Latvia","assets/flags/latvia-flag-icon-32.png"),
Country("Lebanon","assets/flags/lebanon-flag-icon-32.png"),
Country("Liberia","assets/flags/liberia-flag-icon-32.png"),
Country("Libya","assets/flags/libya-flag-icon-32.png"),
Country("Liechtenstein","assets/flags/liechtenstein-flag-icon-32.png"),
Country("Lithuania","assets/flags/lithuania-flag-icon-32.png"),
Country("Luxembourg","assets/flags/luxembourg-flag-icon-32.png"),
Country("Macedonia","assets/flags/macedonia-flag-icon-32.png"),
Country("Madagascar","assets/flags/madagascar-flag-icon-32.png"),
Country("Malawi","assets/flags/malawi-flag-icon-32.png"),
Country("Malaysia","assets/flags/malaysia-flag-icon-32.png"),
Country("Mali","assets/flags/mali-flag-icon-32.png"),
Country("Malta","assets/flags/malta-flag-icon-32.png"),
Country("Maldives","assets/flags/maldives-flag-icon-32.png"),
Country("Mauritania","assets/flags/mauritania-flag-icon-32.png"),
Country("Mauritius","assets/flags/mauritius-flag-icon-32.png"),
Country("Mexico","assets/flags/mexico-flag-icon-32.png"),
Country("Moldova","assets/flags/moldova-flag-icon-32.png"),
Country("Monaco","assets/flags/monaco-flag-icon-32.png"),
Country("Mongolia","assets/flags/mongolia-flag-icon-32.png"),
Country("Montenegro","assets/flags/montenegro-flag-icon-32.png"),
Country("Morocco","assets/flags/morocco-flag-icon-32.png"),
Country("Mozambique","assets/flags/mozambique-flag-icon-32.png"),
Country("Namibia","assets/flags/namibia-flag-icon-32.png"),
Country("New Zealand","assets/flags/new-zealand-flag-icon-32.png"),
Country("Nicaragua","assets/flags/nicaragua-flag-icon-32.png"),
Country("Niger","assets/flags/niger-flag-icon-32.png"),
Country("Nigeria","assets/flags/nigeria-flag-icon-32.png"),
Country("North Korea","assets/flags/north-korea-flag-icon-32.png"),
Country("Norway","assets/flags/norway-flag-icon-32.png"),
Country("Oman","assets/flags/oman-flag-icon-32.png"),
Country("Pakistan","assets/flags/pakistan-flag-icon-32.png"),
Country("Panama","assets/flags/panama-flag-icon-32.png"),
Country("Papua New Guinea","assets/flags/papua-new-guinea-flag-icon-32.png"),
Country("Paraguay","assets/flags/paraguay-flag-icon-32.png"),
Country("Peru","assets/flags/peru-flag-icon-32.png"),
Country("Philippines","assets/flags/philippines-flag-icon-32.png"),
Country("Poland","assets/flags/poland-flag-icon-32.png"),
Country("Portugal","assets/flags/portugal-flag-icon-32.png"),
Country("Puerto Rico","assets/flags/puerto-rico-flag-icon-32.png"),
Country("Qatar","assets/flags/qatar-flag-icon-32.png"),
Country("Romania","assets/flags/romania-flag-icon-32.png"),
Country("Russia","assets/flags/russia-flag-icon-32.png"),
Country("Rwanda","assets/flags/rwanda-flag-icon-32.png"),
Country("Saudi Arabia","assets/flags/saudi-arabia-flag-icon-32.png"),
Country("Scotland","assets/flags/scotland-flag-icon-32.png"),
Country("Senegal","assets/flags/senegal-flag-icon-32.png"),
Country("serbia","assets/flags/serbia-flag-icon-32.png"),
Country("Seychelles","assets/flags/seychelles-flag-icon-32.png"),
Country("Sierra Leone","assets/flags/sierra-leone-flag-icon-32.png"),
Country("Singapore","assets/flags/singapore-flag-icon-32.png"),
Country("Slovakia","assets/flags/slovakia-flag-icon-32.png"),
Country("Slovenia","assets/flags/slovenia-flag-icon-32.png"),
Country("Solomon Islands","assets/flags/solomon-islands-flag-icon-32.png"),
Country("Somalia","assets/flags/somalia-flag-icon-32.png"),
Country("South Africa","assets/flags/south-africa-flag-icon-32.png"),
Country("South Korea","assets/flags/south-korea-flag-icon-32.png"),
Country("Spain","assets/flags/spain-flag-icon-32.png"),
Country("SriLanka","assets/flags/sriLanka-flag-icon-32.png"),
Country("Sudan","assets/flags/sudan-flag-icon-32.png"),
Country("Suriname","assets/flags/suriname-flag-icon-32.png"),
Country("Swaziland","assets/flags/swaziland-flag-icon-32.png"),
Country("Sweden","assets/flags/sweden-flag-icon-32.png"),
Country("Switzerland","assets/flags/switzerland-flag-icon-32.png"),
Country("Syria","assets/flags/syria-flag-icon-32.png"),
Country("Taiwan","assets/flags/taiwan-flag-icon-32.png"),
Country("Tanzania","assets/flags/tanzania-flag-icon-32.png"),
Country("Thailand","assets/flags/thailand-flag-icon-32.png"),
Country("Togo","assets/flags/togo-flag-icon-32.png"),
Country("Trinidad and Tobago","assets/flags/trinidad-and-tobago-flag-icon-32.png"),
Country("Tunisia","assets/flags/tunisia-flag-icon-32.png"),
Country("Turkey","assets/flags/turkey-flag-icon-32.png"),
Country("Turkmenistan","assets/flags/turkmenistan-flag-icon-32.png"),
Country("Tuvalu","assets/flags/tuvalu-flag-icon-32.png"),
Country("Uganda","assets/flags/uganda-flag-icon-32.png"),
Country("Ukraine","assets/flags/ukraine-flag-icon-32.png"),
Country("United Arab Emirates","assets/flags/united-arab-emirates-flag-icon-32.png"),
Country("United Kingdom","assets/flags/united-kingdom-flag-icon-32.png"),
Country("United States Of America","assets/flags/united-states-of-america-flag-icon-32.png"),
Country("Uruguay","assets/flags/uruguay-flag-icon-32.png"),
Country("Uzbekistan","assets/flags/uzbekistan-flag-icon-32.png"),
Country("Vanuatu","assets/flags/vanuatu-flag-icon-32.png"),
Country("Vatican","assets/flags/vatican-city-flag-icon-32.png"),
Country("Venezuela","assets/flags/venezuela-flag-icon-32.png"),
Country("Vietnam","assets/flags/vietnam-flag-icon-32.png"),
Country("Samoa","assets/flags/samoa-flag-icon-32.png"),
Country("Yemen","assets/flags/yemen-flag-icon-32.png"),
Country("Yugoslavia","assets/flags/yugoslavia-flag-icon-32.png"),
Country("Zaire","assets/flags/zaire-flag-icon-32.png"),
Country("Zambia","assets/flags/zambia-flag-icon-32.png"),
Country("Zimbabwe","assets/flags/zimbabwe-flag-icon-32.png"),
];

class CountrySelectList extends StatefulWidget {
  @override
  _CountrySelectListState createState() =>
      _CountrySelectListState();
}

class _CountrySelectListState extends State<CountrySelectList> {

  @override
  Widget build(BuildContext context) {
    return SingleChildScrollView(
      padding: EdgeInsets.all(20),
      child: Column(children: [
        SizedBox(height: 10,),
        ...countries.map((Country country) {
          return GestureDetector(
            onTap: () {
              Navigator.pop(context, country);
            },
            child: Container(
                child: Padding(
              padding: const EdgeInsets.all(10.0),
              child: Row(children: [
                Image.asset(
                  country.flag,
                  width: 30,
                ),
                SizedBox(width: 10),
                Text(country.name)
              ]),
            )),
          );
        }).toList(),
      ]),
    );
  }
}