import 'package:flutter/material.dart';

class Country {
  final String name;
  final String flag;

  Country(this.name, this.flag);
}

List<Country> countries = [
Country("Afghanistan", "assets/flag/afghanistan-flag-icon-32"),
Country("Albania","assets/flags/albania-flag-icon-32.png" ),
Country("Algeria","assets/flags/algeria-flag-icon-32.png" ),
Country("Andorra","assets/flags/angola-flag-icon-32.png" ),
Country("Angola","assets/flags/angola-flag-icon-32.png" ),
/*Country("Argentina","https://cdn.countryflags.com/thumbs/argentina/flag-800.png" ),
Country("Armenia"," https://cdn.countryflags.com/thumbs/armenia/flag-800.png" ),
Country("Australia","https://cdn.countryflags.com/thumbs/australia/flag-800.png" ),
Country("Austria","https://cdn.countryflags.com/thumbs/austria/flag-800.png " ),
Country("Azerbaijan","https://cdn.countryflags.com/thumbs/azerbaijan/flag-800.png " ),
Country("Bahamas","https://cdn.countryflags.com/thumbs/bahamas/flag-800.png " ),
Country("Bahrain","https://cdn.countryflags.com/thumbs/bahrain/flag-800.png " ),
Country("Bangladesh","https://cdn.countryflags.com/thumbs/bangladesh/flag-800.png " ),
Country("Barbados","https://cdn.countryflags.com/thumbs/barbados/flag-800.png " ),
Country("Belarus","https://cdn.countryflags.com/thumbs/belarus/flag-800.png " ),
Country("Belgium","https://cdn.countryflags.com/thumbs/belgium/flag-800.png" ),
Country("Belize","https://cdn.countryflags.com/thumbs/belize/flag-800.png " ),
Country("Benin","https://cdn.countryflags.com/thumbs/benin/flag-800.png" ),
Country("Bhutan","https://cdn.countryflags.com/thumbs/bhutan/flag-800.png " ),
Country("Bolivia","https://cdn.countryflags.com/thumbs/bolivia/flag-800.png " ),
Country("Bosnia and Herzegovina"," https://cdn.countryflags.com/thumbs/bosnia-and-herzegovina/flag-800.png" ),
Country("Botswana","https://cdn.countryflags.com/thumbs/botswana/flag-800.png " ),
Country("Brazil","https://cdn.countryflags.com/thumbs/brazil/flag-800.png" ),
Country("Brunei","https://cdn.countryflags.com/thumbs/brunei/flag-800.png " ),
Country("Bulgaria","https://cdn.countryflags.com/thumbs/bulgaria/flag-800.png " ),
Country("Burkina","https://cdn.countryflags.com/thumbs/burkina/flag-800.png " ),
Country("Burma","https://cdn.countryflags.com/thumbs/burma/flag-800.png " ),
Country("Burundi","https://cdn.countryflags.com/thumbs/burundi/flag-800.png " ),
Country("Cambodia","https://cdn.countryflags.com/thumbs/cambodia/flag-800.png " ),
Country("Cameroon","https://cdn.countryflags.com/thumbs/cameroon/flag-800.png " ),
Country("Canada","https://cdn.countryflags.com/thumbs/canada/flag-800.png " ),
Country("Cape Verde"," https://cdn.countryflags.com/thumbs/cape-verde/flag-800.png" ),
Country("Chad","https://cdn.countryflags.com/thumbs/chad/flag-800.png " ),
Country("Chile","https://cdn.countryflags.com/thumbs/chile/flag-800.png" ),
Country("China","https://cdn.countryflags.com/thumbs/china/flag-800.png" ),
Country("Colombia","https://cdn.countryflags.com/thumbs/colombia/flag-800.png " ),
Country("Congo","https://cdn.countryflags.com/thumbs/congo-democratic-republic-of-the/flag-800.png " ),
Country("Costa Rica","https://cdn.countryflags.com/thumbs/costa-rica/flag-800.png " ),
Country("Croatia","https://cdn.countryflags.com/thumbs/croatia/flag-800.png " ),
Country("Cuba"," https://cdn.countryflags.com/thumbs/cuba/flag-800.png" ),
Country("Cyprus"," https://cdn.countryflags.com/thumbs/cyprus/flag-800.png" ),
Country("Czech Republic"," https://cdn.countryflags.com/thumbs/czech-republic/flag-800.png" ),
Country("Denmark","https://cdn.countryflags.com/thumbs/denmark/flag-800.png " ),
Country("Djibouti"," https://cdn.countryflags.com/thumbs/djibouti/flag-800.png" ),
Country("Dominica","https://cdn.countryflags.com/thumbs/dominica/flag-800.png " ),
Country("Dominican Republic","https://cdn.countryflags.com/thumbs/dominican-republic/flag-800.png " ),
Country("Ecuador","https://cdn.countryflags.com/thumbs/ecuador/flag-800.png " ),
Country("Egypt","https://cdn.countryflags.com/thumbs/egypt/flag-800.png " ),
Country("El Salvador"," https://cdn.countryflags.com/thumbs/el-salvador/flag-800.png" ),
Country("England","https://cdn.countryflags.com/thumbs/england/flag-800.png " ),
Country("Eritrea","https://cdn.countryflags.com/thumbs/eritrea/flag-800.png " ),
Country("Estonia","https://cdn.countryflags.com/thumbs/estonia/flag-800.png " ),
Country("Ethiopia"," https://cdn.countryflags.com/thumbs/ethiopia/flag-800.png" ),
Country("Fiji"," https://cdn.countryflags.com/thumbs/fiji/flag-800.png" ),
Country("Finland","https://cdn.countryflags.com/thumbs/finland/flag-800.png " ),
Country("France","https://cdn.countryflags.com/thumbs/france/flag-800.png " ),
Country("Gabon"," https://cdn.countryflags.com/thumbs/gabon/flag-800.png" ),
Country("Gambia"," https://cdn.countryflags.com/thumbs/gambia/flag-800.png" ),
Country("Georgia","https://cdn.countryflags.com/thumbs/georgia/flag-800.png " ),
Country("Germany","https://cdn.countryflags.com/thumbs/germany/flag-800.png " ),
Country("Ghana","https://cdn.countryflags.com/thumbs/ghana/flag-800.png " ),
Country("Greece","https://cdn.countryflags.com/thumbs/greece/flag-800.png " ),
Country("Grenada","https://cdn.countryflags.com/thumbs/grenada/flag-800.png " ),
Country("Guatemala","https://cdn.countryflags.com/thumbs/guatemala/flag-800.png " ),
Country("Guinea","https://cdn.countryflags.com/thumbs/guinea/flag-800.png " ),
Country("Guyana","https://cdn.countryflags.com/thumbs/guyana/flag-800.png " ),
Country("Haiti","https://cdn.countryflags.com/thumbs/haiti/flag-800.png " ),
Country("Holland","https://cdn.countryflags.com/thumbs/holland/flag-800.png " ),
Country("Honduras","https://cdn.countryflags.com/thumbs/honduras/flag-800.png " ),
Country("Hungary","https://cdn.countryflags.com/thumbs/hungary/flag-800.png " ),
Country("Iceland","https://cdn.countryflags.com/thumbs/iceland/flag-800.png " ),
Country("India","https://cdn.countryflags.com/thumbs/india/flag-800.png " ),
Country("Indonesia","https://cdn.countryflags.com/thumbs/indonesia/flag-800.png " ),
Country("Iran","https://cdn.countryflags.com/thumbs/iran/flag-800.png " ),
Country("Iraq","https://cdn.countryflags.com/thumbs/iraq/flag-800.png " ),
Country("Ireland","https://cdn.countryflags.com/thumbs/ireland/flag-800.png " ),
Country("Israel","https://cdn.countryflags.com/thumbs/israel/flag-800.png " ),
Country("Italy","https://cdn.countryflags.com/thumbs/italy/flag-800.png " ),
Country("Japan","https://cdn.countryflags.com/thumbs/japan/flag-800.png " ),
Country("Jordan","https://cdn.countryflags.com/thumbs/jordan/flag-800.png " ),
Country("Kazakhstan","https://cdn.countryflags.com/thumbs/kazakhstan/flag-800.png " ),
Country("Kenya","https://cdn.countryflags.com/thumbs/kenya/flag-800.png " ),
Country("Korea","https://cdn.countryflags.com/thumbs/korea/flag-800.png " ),
Country("Kuwait","https://cdn.countryflags.com/thumbs/kuwait/flag-800.png " ),
Country("Laos","https://cdn.countryflags.com/thumbs/laos/flag-800.png " ),
Country("Latvia","https://cdn.countryflags.com/thumbs/latvia/flag-800.png " ),
Country("Lebanon","https://cdn.countryflags.com/thumbs/lebanon/flag-800.png " ),
Country("Liberia","https://cdn.countryflags.com/thumbs/liberia/flag-800.png " ),
Country("Libya","https://cdn.countryflags.com/thumbs/libya/flag-800.png " ),
Country("Liechtenstein","https://cdn.countryflags.com/thumbs/liechtenstein/flag-800.png " ),
Country("Lithuania","https://cdn.countryflags.com/thumbs/lithuania/flag-800.png " ),
Country("Luxembourg","https://cdn.countryflags.com/thumbs/luxembourg/flag-800.png " ),
Country("Macedonia","https://cdn.countryflags.com/thumbs/macedonia/flag-800.png " ),
Country("Madasgascar","https://cdn.countryflags.com/thumbs/madasgascar/flag-800.png " ),
Country("Malawi","https://cdn.countryflags.com/thumbs/malawi/flag-800.png " ),
Country("Malaysia","https://cdn.countryflags.com/thumbs/malaysia/flag-800.png " ),
Country("Mali","https://cdn.countryflags.com/thumbs/mali/flag-800.png " ),
Country("Malta","https://cdn.countryflags.com/thumbs/malta/flag-800.png " ),
Country("Maldives","https://cdn.countryflags.com/thumbs/maldives/flag-800.png " ),
Country("Mauritania","https://cdn.countryflags.com/thumbs/mauritania/flag-800.png " ),
Country("Mauritius","https://cdn.countryflags.com/thumbs/mauritius/flag-800.png " ),
Country("Mexico","https://cdn.countryflags.com/thumbs/mexico/flag-800.png " ),
Country("Moldova","https://cdn.countryflags.com/thumbs/moldova/flag-800.png " ),
Country("Monaco","https://cdn.countryflags.com/thumbs/monaco/flag-800.png " ),
Country("Mongolia","https://cdn.countryflags.com/thumbs/mongolia/flag-800.png " ),
Country("Montenegro"," https://cdn.countryflags.com/thumbs/montenegro/flag-800.png" ),
Country("Morocco","https://cdn.countryflags.com/thumbs/morocco/flag-800.png " ),
Country("Mozambique","https://cdn.countryflags.com/thumbs/mozambique/flag-800.png" ),
Country("Namibia","https://cdn.countryflags.com/thumbs/namibia/flag-800.png " ),
Country("New Zealand","https://cdn.countryflags.com/thumbs/new-zealand/flag-800.png " ),
Country("Nicaragua"," https://cdn.countryflags.com/thumbs/nicaragua/flag-800.png" ),
Country("Niger","https://cdn.countryflags.com/thumbs/niger/flag-800.png " ),
Country("Nigeria","https://cdn.countryflags.com/thumbs/nigeria/flag-800.png " ),
Country("North Korea"," https://cdn.countryflags.com/thumbs/north-korea/flag-800.png" ),
Country("Norway","https://cdn.countryflags.com/thumbs/norway/flag-800.png " ),
Country("Oman","https://cdn.countryflags.com/thumbs/oman/flag-800.png " ),
Country("Pakistan","https://cdn.countryflags.com/thumbs/pakistan/flag-800.png " ),
Country("Panama"," https://cdn.countryflags.com/thumbs/panama/flag-800.png" ),
Country("Papua New Guinea"," https://cdn.countryflags.com/thumbs/papua-new-guinea/flag-800.png" ),
Country("Paraguay","https://cdn.countryflags.com/thumbs/paraguay/flag-800.png " ),
Country("Peru"," https://cdn.countryflags.com/thumbs/peru/flag-800.png" ),
Country("Philippines","https://cdn.countryflags.com/thumbs/philippines/flag-800.png " ),
Country("Poland","https://cdn.countryflags.com/thumbs/poland/flag-800.png " ),
Country("Portugal"," https://cdn.countryflags.com/thumbs/portugal/flag-800.png" ),
Country("Puerto Rico"," https://cdn.countryflags.com/thumbs/puerto-rico/flag-800.png" ),
Country("Qatar","https://cdn.countryflags.com/thumbs/qatar/flag-800.png " ),
Country("Romania","https://cdn.countryflags.com/thumbs/romania/flag-800.png " ),
Country("Russia","https://cdn.countryflags.com/thumbs/russia/flag-800.png " ),
Country("Rwanda","https://cdn.countryflags.com/thumbs/rwanda/flag-800.png " ),
Country("Saudi Arabia","https://cdn.countryflags.com/thumbs/saudi-arabia/flag-800.png " ),
Country("Scotland","https://cdn.countryflags.com/thumbs/scotland/flag-800.png " ),
Country("Senegal","https://cdn.countryflags.com/thumbs/senegal/flag-800.png " ),
Country("serbia","https://cdn.countryflags.com/thumbs/serbia/flag-800.png " ),
Country("Seychelles"," https://cdn.countryflags.com/thumbs/seychelles/flag-800.png" ),
Country("SierraLeone","https://cdn.countryflags.com/thumbs/sierraLeone/flag-800.png " ),
Country("Singapore","https://cdn.countryflags.com/thumbs/singapore/flag-800.png " ),
Country("Slovakia","https://cdn.countryflags.com/thumbs/slovakia/flag-800.png " ),
Country("Slovenia"," https://cdn.countryflags.com/thumbs/slovenia/flag-800.png" ),
Country("Solomon Islands"," https://cdn.countryflags.com/thumbs/solomon-islands/flag-800.png" ),
Country("Somalia","https://cdn.countryflags.com/thumbs/somalia/flag-800.png " ),
Country("South Africa","https://cdn.countryflags.com/thumbs/south-africa/flag-800.png " ),
Country("South Korea","https://cdn.countryflags.com/thumbs/south-korea/flag-800.png " ),
Country("Spain","https://cdn.countryflags.com/thumbs/spain/flag-800.png " ),
Country("SriLanka"," https://cdn.countryflags.com/thumbs/sriLanka/flag-800.png" ),
Country("Sudan","https://cdn.countryflags.com/thumbs/sudan/flag-800.png " ),
Country("Suriname"," https://cdn.countryflags.com/thumbs/suriname/flag-800.png" ),
Country("Swaziland"," https://cdn.countryflags.com/thumbs/swaziland/flag-800.png" ),
Country("Sweden","https://cdn.countryflags.com/thumbs/sweden/flag-800.png " ),
Country("Switzerland","https://cdn.countryflags.com/thumbs/switzerland/flag-800.png " ),
Country("Syria","https://cdn.countryflags.com/thumbs/syria/flag-800.png " ),
Country("Taiwan"," https://cdn.countryflags.com/thumbs/taiwan/flag-800.png" ),
Country("Tanzania"," https://cdn.countryflags.com/thumbs/tanzania/flag-800.png" ),
Country("thailand","https://cdn.countryflags.com/thumbs/thailand/flag-800.png " ),
Country("Togo"," https://cdn.countryflags.com/thumbs/togo/flag-800.png" ),
Country("Trinidad and Tobago","https://cdn.countryflags.com/thumbs/trinidad-and-tobago/flag-800.png " ),
Country("Tunisia","https://cdn.countryflags.com/thumbs/tunisia/flag-800.png " ),
Country("Turkey","https://cdn.countryflags.com/thumbs/turkey/flag-800.png " ),
Country("Turkmenistan","https://cdn.countryflags.com/thumbs/turkmenistan/flag-800.png " ),
Country("Tuvalu","https://cdn.countryflags.com/thumbs/tuvalu/flag-800.png " ),
Country("Uganda","https://cdn.countryflags.com/thumbs/uganda/flag-800.png " ),
Country("Ukraine","https://cdn.countryflags.com/thumbs/ukraine/flag-800.png " ),
Country("United Arab Emirates","https://cdn.countryflags.com/thumbs/united-arab-emirates/flag-800.png " ),
Country("United Kingdom","https://cdn.countryflags.com/thumbs/united-kingdom/flag-800.png "),
Country("United States","https://cdn.countryflags.com/thumbs/united-states/flag-800.png " ),
Country("Uruguay","https://cdn.countryflags.com/thumbs/uruguay/flag-800.png " ),
Country("Uzbekistan"," https://cdn.countryflags.com/thumbs/uzbekistan/flag-800.png" ),
Country("Vanuatu","https://cdn.countryflags.com/thumbs/vanuatu/flag-800.png " ),
Country("Vatican","https://cdn.countryflags.com/thumbs/vatican/flag-800.png " ),
Country("Venezuela","https://cdn.countryflags.com/thumbs/venezuela/flag-800.png " ),
Country("Vietnam","https://cdn.countryflags.com/thumbs/vietnam/flag-800.png " ),
Country("Samoa"," https://cdn.countryflags.com/thumbs/samoa/flag-800.png" ),
Country("Yemen","https://cdn.countryflags.com/thumbs/yemen/flag-800.png " ),
Country("Yugoslavia","https://cdn.countryflags.com/thumbs/yugoslavia/flag-800.png " ),
Country("Zaire","https://cdn.countryflags.com/thumbs/zaire/flag-800.png " ),
Country("Zambia","https://cdn.countryflags.com/thumbs/zambia/flag-800.png " ),
Country("Zimbabwe"," https://cdn.countryflags.com/thumbs/zimbabwe/flag-800.png" ),*/
];

class CountrySelectList extends StatefulWidget {
  @override
  _CountrySelectListState createState() =>
      _CountrySelectListState();
}

class _CountrySelectListState extends State<CountrySelectList> {

  @override
  Widget build(BuildContext context) {
    return SingleChildScrollView(
      padding: EdgeInsets.all(20),
      child: Column(children: [
        Text("Select your country"),
        ...countries.map((Country country) {
          return GestureDetector(
            onTap: () {
              Navigator.pop(context, country);
            },
            child: Container(
                child: Padding(
              padding: const EdgeInsets.all(8.0),
              child: Row(children: [
                Image.network(
                  country.flag,
                  width: 30,
                ),
                SizedBox(width: 10),
                Text(country.name)
              ]),
            )),
          );
        }).toList(),
      ]),
    );
  }
}